// APP REDUCER
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

// QUESTIONNAIRE REDUCER
export const SET_IS_EDITING = 'SET_IS_EDITING';
export const GET_QUESTIONNAIRE = 'GET_QUESTIONNAIRE';
export const GET_QUESTIONNAIRE_SUCCESS = 'GET_QUESTIONNAIRE_SUCCESS';
export const GET_QUESTIONNAIRE_ERROR = 'GET_QUESTIONNAIRE_ERROR';
export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE';
export const SAVE_QUESTIONNAIRE_SUCCESS = 'SAVE_QUESTIONNAIRE_SUCCESS';
export const SAVE_QUESTIONNAIRE_ERROR = 'SAVE_QUESTIONNAIRE_ERROR';
export const CLEAR_QUESTIONNAIRE = 'CLEAR_QUESTIONNAIRE';
